# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwift+MVVM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwift+MVVM
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxRelay'
  pod 'RxOptional'
  pod 'RxViewController'

  target 'RxSwift+MVVMTests' do
    inherit! :search_paths
    pod 'RxTest'
    pod 'RxBlocking'
  end

end
